name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  anchor_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: metadaoproject/anchor-test@v2
        with:
          anchor-version: '0.29.0'
          solana-cli-version: '1.18.11'
          node-version: '22'
          features: 'anchor-test'
      - run: cargo fmt -- --check && cargo clippy
      - run: cargo test
      - run: anchor build && npm ci && npm run test -- run
